Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@mcsnyk 
mcsnyk
/
gin
Public
forked from gin-gonic/gin
Fork your own copy of mcsnyk/gin
Code
Pull requests
Actions
Projects
Security
Insights
Settings
gin/.github/workflows/snyk.yml
@mcsnyk
mcsnyk Update and rename codeql.yml to snyk.yml
Latest commit cd523d1 3 minutes ago
 History
 1 contributor
47 lines (39 sloc)  1.1 KB

name: "Snyk"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install snyk -g
      - run: snyk -v
      - run: snyk auth ${{ secrets.SNYK_TOKEN }} 

        # Generate the HTML report
      - name: install snyk-to-html
        run: |
            npm install snyk-to-html -g
            snyk monitor --all-projects --org=a6fc236b-fcdf-46d3-8425-5e3a76366a1f
            snyk test --json | snyk-to-html -o result.html
            mkdir downloads
            cp -v /home/runner/work/gin/gin/*.html /home/runner/work/gin/gin/downloads
      # save the HTML in the artifact
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: downloads
gin/snyk.yml at master · mcsnyk/gin
